name: 'InsuranceAnalyticsPipeline'
version: '1.0.0'
config-version: 2

profile: 'InsuranceAnalyticsPipeline'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analyses"]

models:
  InsuranceAnalyticsPipeline:
    +materialized: view

seeds:
  InsuranceAnalyticsPipeline:
    +schema: dbo